import { formattedDateNow } from "../src/libs/DateFormat";
import { PrismaClient, product_type } from "@prisma/client";

const bcrypt = require("bcrypt");
const prisma = new PrismaClient();

async function main() {
  const data = [
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 1 }],
      sell_price: 650000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 2 }],
      sell_price: 850000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 3 }],
      sell_price: 950000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 4 }],
      sell_price: 1150000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 5 }],
      sell_price: 1300000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 6 }],
      sell_price: 1500000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 7 }],
      sell_price: 1550000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 8 }],
      sell_price: 1750000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 9 }],
      sell_price: 1850000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 10 }],
      sell_price: 1900000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 11 }],
      sell_price: 1950000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 12 }],
      sell_price: 2100000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 13 }],
      sell_price: 2300000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 14 }, { id: 15 }],
      sell_price: 2500000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 16 }],
      sell_price: 2700000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 17 }],
      sell_price: 2900000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 18 }],
      sell_price: 3000000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 19 }],
      sell_price: 1800000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 20 }],
      sell_price: 3100000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 21 }],
      sell_price: 3300000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 22 }],
      sell_price: 3500000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 23 }],
      sell_price: 3800000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 24 }],
      sell_price: 4000000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 25 }],
      sell_price: 4300000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 26 }, { id: 27 }],
      sell_price: 4500000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 28 }],
      sell_price: 4800000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 29 }],
      sell_price: 5100000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
    {
      name: "SWAP BOARD",
      product_type: "MACHINE",
      category: {
        id: 17,
      },
      device_type: "IPHONE",
      device: [{ id: 30 }],
      sell_price: 5400000,
      warranty: 90,
      is_pos: true,
      is_inventory: false,
      is_show_portal: true,
    },
  ];

  for (let i = 0; i < data.length; i++) {
    await prisma.product.create({
      data: {
        name: data[i].name,
        sell_price: data[i].sell_price,
        warranty: data[i].warranty,
        is_pos: data[i].is_pos,
        is_inventory: data[i].is_inventory,
        is_show_portal: data[i].is_show_portal,
        product_type: data[i].product_type as product_type,
        product_category: {
          create: [
            {
              category_id: data[i].category.id,
            },
          ],
        },
        product_device: {
          create: data[i].device?.map((item: any) => ({
            device_id: item.id,
          })),
        },
        created_at: formattedDateNow(),
        branch_id: 1,
      },
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.log(e);
    await prisma.$disconnect();
    process.exit(1);
  });
